### PR TITLE
new function prototypes for click/change events

### PR DESCRIPTION
**Pull request by Masterdanielsan**

### CODE REVIEW

**Comment by uqee** [comment]
You propose to just remove everything?) Have a look at [Files changed](https://github.com/uqee/angular-evaporate/pull/18/files) tab.

**Comment by Masterdanielsan** [comment]
trying to make PR for change / click prototype changes

**Comment by uqee** [comment]
Well, unfortunately that PR shouldn't be merged because it just duplicates an already existing Angular core functionality. The proper way to watch for click and change events would be using the [`ng-click`](https://docs.angularjs.org/api/ng/directive/ngClick) and [`ng-change`](https://docs.angularjs.org/api/ng/directive/ngChange) directives respectively (also speaking about your use case and the latter directive, be aware of [that issue](https://github.com/angular/angular.js/issues/1375)).

**Comment by Masterdanielsan** [comment]
The ng-click and ng-change directives do not work when added as attributes to the angular-evaporate directive.  The change I added seems to work fine.

Can you offer an alternative?

The following DOES NOT work:
`<input type="file" style="display:none;" multiple angular-evaporate="ae" **ng-change="previewFiles()"**>`

Additionally, I have seen that issue that you linked, but it didn't seem to effect the code I added...

Thoughts?

---

EDIT: ng-click works fine.  ng-change does not work currently.  Currently there is no way to register that the input has changed without altering the directive.  I believe this change (without the click portion) should go live.

**Comment by uqee** [comment]
As guys discuss it in the issue above, you have to use a native `onchange` instead of `ng-change` in case of `input[type=file]` until it gets fixed in the Angular core (currently work in progress). This functionality has nothing in common with the current directive, so it shouldn't be included.

**Pull request closed without merging**
